# MACROS

MPICC   = mpicc

# DEPENDENCIES

graf_dist_min_trat_msgs_vzs.exe: graf_dist_min_trat_msgs_vzs.c
	$(MPICC) graf_dist_min_trat_msgs_vzs.c -o graf_dist_min_trat_msgs_vzs.exe 
	@echo Compilado com Sucesso!

clean:
	rm -f core graf_dist_min_trat_msgs_vzs.exe 
	

