# MACROS

MPICC   = mpicc

# DEPENDENCIES

integr_trapez_trat_rest.exe: integr_trapez_trat_rest.c
	$(MPICC) integr_trapez_trat_rest.c -o integr_trapez_trat_rest.exe -lm
	@echo Compilado com Sucesso!

clean:
	rm -f core integr_trapez_trat_rest.exe
