# MACROS

MPICC   = mpicc

# DEPENDENCIES

a_mutually_exclude_c.exe: a_mutually_exclude_c.c
	$(MPICC) a_mutually_exclude_c.c -o a_mutually_exclude_c.exe 
	@echo Compilado com Sucesso!

clean:
	rm -f core a_mutually_exclude_c.exe 
	

