# MACROS

MPICC   = mpicc

# DEPENDENCIES

a_mutually_exclude.exe: a_mutually_exclude.c
	$(MPICC) a_mutually_exclude.c -o a_mutually_exclude.exe 
	@echo Compilado com Sucesso!

clean:
	rm -f core a_mutually_exclude.exe 
	

